#!/bin/bash

# Check if there are changes in the template/ directory
if git diff --name-only --cached | grep -q '^template/.*\.cpp$'; then
    echo "Changes detected in template/. Regenerating snippets..."
    python3 scripts/code-snippets-format-converter.py

    # Add the updated snippets file to the commit
    git add .vscode/cpp.code-snippets
fi